# fly.toml app configuration file generated for realtimedoccolabplatform on 2025-01-24T15:47:02Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.

app = "realtimedoccolabplatform"
primary_region = "iad"

[build]

[env]
  ENV = "production"
  DYNAMODB_LOCAL = "false"
  PORT = "8080"
  LOG_LEVEL = "info"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[[http_service.checks]]
  grace_period = "10s"
  interval = "30s"
  method = "GET"
  timeout = "5s"
  path = "/health"

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 512
