# fly.toml app configuration file for realtimedoccolabplatform
app = "realtimedoccolabplatform"
primary_region = "iad"

[build]
  dockerfile = "Dockerfile.fly"

[env]
  ENV = "production"
  DYNAMODB_LOCAL = "false"
  PORT = "8080"
  LOG_LEVEL = "info"

[processes]
  app = "main"

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 512

[[services]]
  protocol = "tcp"
  internal_port = 8080
  processes = ["app"]

  [[services.ports]]
    port = 80
    handlers = ["http"]

  [[services.ports]]
    port = 443
    handlers = ["tls", "http"]

  [[services.tcp_checks]]
    grace_period = "10s"
    interval = "30s"
    timeout = "5s"
